In [6]:
#Question .21

import numpy as np
from sklearn.preprocessing import Binarizer

data = np.array([[1.5, 0.7, 2.3],
                 [2.0, 0.2, 1.8],
                 [0.5, 0.9, 1.6]])

threshold = 1.0
binarizer = Binarizer(threshold=threshold)
binary_data = binarizer.transform(data)

print("Original data:\n", data)
print("\nBinary data (threshold = {}):\n".format(threshold), binary_data)



Original data:
 [[1.5 0.7 2.3]
 [2.  0.2 1.8]
 [0.5 0.9 1.6]]

Binary data (threshold = 1.0):
 [[1. 0. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]


In [4]:
#Question .22

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Step 1: Load Data
iris = load_iris()
X = iris.data
y = iris.target

# Step 2: Preprocess Data (Not necessary for Iris dataset)

# Step 3: Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 4: Create KNN Model
k = 3  # Number of neighbors
knn_model = KNeighborsClassifier(n_neighbors=k)

# Step 5: Train Model
knn_model.fit(X_train, y_train)

# Step 6: Evaluate Model
y_pred = knn_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)





Accuracy: 1.0


In [1]:
#Question .23

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)


Shape of X_train: (120, 4)
Shape of X_test: (30, 4)
Shape of y_train: (120,)
Shape of y_test: (30,)


In [2]:
# Question .24

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)


Shape of X_train: (105, 4)
Shape of X_test: (45, 4)
Shape of y_train: (105,)
Shape of y_test: (45,)


In [3]:
#question .25

import pandas as pd
from sklearn.preprocessing import LabelEncoder

iris = load_iris()
X = iris.data
y = iris.target

label_encoder = LabelEncoder()
y_numerical = label_encoder.fit_transform(y)

iris_df = pd.DataFrame(data=X, columns=iris.feature_names)
iris_df['species'] = y_numerical

print("First 5 rows of the DataFrame:")
print(iris_df.head())


First 5 rows of the DataFrame:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  
